import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from './container/Header';
import { Providers } from './providers';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SiRoMeIs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>
          <Header />
          <div className="mt-[-96px] flex min-h-screen w-full justify-center bg-kopa-background pt-20">
            <div className="w-[1320px]">{children}</div>
          </div>
        </Providers>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
