export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_REFRESH = 'AUTH_REFRESH';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS';
export const GET_FILTERED_PROJECTS = 'GET_FILTERED_PROJECTS';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
